config/routes.rb
FinalNexi::Application.routes.draw do
  

  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login" }

  resources :ads

  resources :articles do
    resources :comments
  end

  resources :pages
  
  root :to => 'pages#index'
 

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :image, :permalink, :page_id
  belongs_to :page
  has_attached_file :image

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :author, :content, :image, :page_id, :tag, :source
  has_many :comments
  belongs_to :page
  has_attached_file :image
  
  
  def to_param
    "#{id}-#{title}"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title
  has_many :articles
  has_many :ads
  
  def to_param
    "#{id}-#{title}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :rpx_connectable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  
  before_filter :authenticate_user! , :except =>  [:show, :index]
  def index
    @ads = Ad.all
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params[:ad])
    if @ad.save
      redirect_to @ad, :notice => "Successfully created ad."
    else
      render :action => 'new'
    end
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update_attributes(params[:ad])
      redirect_to @ad, :notice  => "Successfully updated ad."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to ads_url, :notice => "Successfully destroyed ad."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :pages, :ads, :display_articles ,:latest_articles, :all_sorted_articles
  def pages
    @pages ||= Page.all  
  end
  
  def ads
    @ads ||= Ad.all
  end
  
  def display_articles
    @display_articles ||= Article.paginate(:page => params[:page], :per_page => 10).scoped.order("created_at DESC")

  end
  
  def latest_articles
    @latest_articles ||= Article.limit(3).scoped.order("created_at DESC")
  end

  def all_sorted_articles
    @all_sorted_articles ||= Article.scoped.order("created_at DESC")
  end
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :authenticate_user! , :except =>  [:show, :index]
  
  def index
    render :layout => 'show_all'
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.paginate(:page => params[:page], :per_page => 10)  
  end

  def new

    @article = Article.new
  end

  def create
  
    @article = Article.new(params[:article])
    if @article.save
      redirect_to @article, :notice => "Successfully created article."
    else
      render :action => 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, :notice  => "Successfully updated article."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, :notice => "Successfully destroyed article."
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   def create  
    article = Article.find params[:article_id]  
    comment = article.comments.new params[:comment]  
    comment.save  
    flash[:notice] = 'Comment saved'  
    redirect_to article_path(article)  
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :authenticate_user! , :except =>  [:show, :index]
  
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
    @page_articles = @page.articles.(paginate :page => params[:page], :per_page => 10)  
    @page_ads = @page.ads.all
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to @page, :notice => "Successfully created page."
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to @page, :notice  => "Successfully updated page."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url, :notice => "Successfully destroyed page."
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ads/_form.html.erb
<%= form_for @ad do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </p>
  <p>
    <%= f.label :page_id %><br />
    <%= f.number_field :page_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/ads/edit.html.erb
<% title "Edit Ad" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
<%= render 'form' %>

<p>
  <%= link_to "Show", @ad %> |
  <%= link_to "View All", ads_path %>
</p>

app/views/ads/index.html.erb
<% title "Ads" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
<table>
  <tr>
    <th>Image</th>
    <th>Permalink</th>
    <th>Page</th>
  </tr>
  <% for ad in @ads %>
    <tr>
      <td><%= image_tag ad.image.url %></td>
      <td><%= ad.permalink %></td>
      <td><%= ad.page_id %></td>
      <td><%= link_to "Show", ad %></td>
      <td><%= link_to "Edit", edit_ad_path(ad) %></td>
            <td> <%= button_to "destroy", ad, :method => :delete %> </td>
      
    </tr>
  <% end %>
</table>

<p><%= link_to "New Ad", new_ad_path %></p>

app/views/ads/new.html.erb
<% title "New Ad" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
<%= render 'form' %>

<p><%= link_to "Back to List", ads_path %></p>

app/views/ads/show.html.erb
<% title "Ad" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
<p>
	<strong>Image:</strong>
	<%= image_tag @ad.image.url %>
</p>
<p>
	<strong>Permalink:</strong>
	<%= @ad.permalink %>
</p>
<p>
	<strong>Page:</strong>
	<%= @ad.page_id %>
</p>
<p>
	<%= link_to "Edit", edit_ad_path(@ad) %> |
	<%= button_to "destroy", @ad, :method => :delete %>|
	<%= link_to "View All", ads_path %>
</p>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.tinymce :content %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :page_id %><br />
    <%= f.text_field :page_id %>
  </p>
  <p>
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </p>
  <p>
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </p>
  <p><%= f.submit :class => 'btn-submit' %></p>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit Article" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">

<%= render 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

app/views/articles/index.html.erb
<% title " All NexInnova Articles" %> <div class="divider_thin"></div>
<!--content -->
<div class="grid_24" style="font-size: 15px; ">
	<table >
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Page</th>
			<th>Tag</th>
			<th>Source</th>
		</tr>
		<% for article in @articles %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.author %></td>
			<td><%= article.page_id %></td>
			<td><%= article.tag %></td>
			<td><%= article.source %></td>
			<td><%= link_to "Show", article %></td>
			<td><%= link_to "Edit", edit_article_path(article) %></td>
			<td> <%= button_to "destroy", article, :method => :delete %> </td>
		</tr>
		<% end %>
	</table>
	<p>
		<%= link_to "New Article", new_article_path %>
	</p>

app/views/articles/new.html.erb
<% title "New Article" %>
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
<%= render 'form' %>

<p><%= link_to "Back to List", articles_path %></p>

app/views/articles/show.html.erb
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
	<div class="cat_title back_post">
		<a href="blog.html" class="link-back">&lt; back to articles</a>
		<div class="social_buttons_top">
			<%= image_tag("temp/social_buttons.gif", :size => '217x20' )%>
		</div>
		<div class="clear"></div>
	</div>
	<!-- post details -->
	<div class="post-item post-detail">
		<h1><%= @article.title %></h1>
		<div class="post-meta">
			<span class="icon_cat icon_cat_blog"><a href="#">Blog</a></span>
			<em>by <span class="author"><%= @article.author %> </span> &nbsp;|&nbsp; on <%= @article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"><%= @article.comments.count %> comments</a></em>
		</div>
		<div class="entry">
			<p>
				<%= image_tag @article.image.url , :size => '590x206' %>
			</p>
			<%= @article.content %> <div class="clear"></div>
		</div>
	</div>
	<!--/ post details -->
	<!-- post comments -->
	<div class="comment-list" id="comments">
		<a href="#addcomments" class="link-addcomment">Add a comment</a>
		<% if @comments %> <h2>Comments (<%= @article.comments.count %>)</h2>
		<ol>
			<% for comment in @article.comments %>
			<li class="comment">
				<div class="comment-body">
					<div class="avatar">
						<%= image_tag("avatar_default.gif", :size => '40x40' )%>
					</div>
					<div class="comment-text">
						<div class="comment-author">
							<a href="#" class="link-author"><%= comment.author %></a> <%= comment.created_at.to_s(:long)%>
						</div>
						<div class="comment-entry">
							<%= comment.text %>
						</div>
					</div>
					<div class="clear"></div>
				</div>
			</li>
			<% end %>
		<%= will_paginate @comments %> 
		<% end %>
		</ol>
	</div>
	<!--/ post comments -->
	<!-- add comment -->
	<div class="add-comment" id="addcomments">
		<h3>Add a comment</h3>
		<div class="comment-form">
			<%= form_for([@article, Comment.new]) do |form| %>
			<div class="row alignleft">
				<label>Your name (required)</label>
				<%= form.text_field :author, :class => "inputtext input_middle required" %>
			</div>
			<div class="clear"></div>
			<div class="row">
				<label>Your message</label>
				<%= form.text_area :text, :class => "textarea textarea_middle required"  %>
			</div>
			<div class="row">
				<%= form.submit 'SUBMIT', :class => 'btn-submit' %>
				<% end %>
			</div>
		</div>
	</div>
	<!--/add comment -->

app/views/layouts/application.html.erb
<!DOCTYPE html UTF-8>
<html>
	<head>
		<%= render "shared/stylesheets" %>
	</head>
	<%= render "shared/headbar" %> <!--/ head menu -->
	<%= render "shared/header" %> <!--/ header -->
	<!-- middle -->
	<div class="middle">
		<div class="container_24">
			<!-- featured list -->
			
				<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>

				<%= yield %> <!--
				<div class="post-item">
				<h2><a href="blog-details.html">Top 5 cool Fashion tips for skinny guys</a></h2>

				<div class="post-meta">
				<span class="icon_cat icon_cat_5"><a href="#">Fashion</a></span>
				<em>by <span class="author">Patrick LeBeouf</span> &nbsp;|&nbsp; on Feb 17th 2011 &nbsp;|&nbsp; <a href="#" class="link-comments">43 comments</a></em>

				</div>

				<div class="entry">
				<p><img src="images/temp/temp_image_4.jpg" alt="" width="235" height="164" class="alignleft" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras adipiscing dignissim tortor, molestie sollicitudin erat ullamcorper eu. Nam ornare pharetra sem vitae blandit. Aliquam sed massa vitae risus sodales molestie vitae sit amet arcu. Nunc egestas leo nec est dapibus a pellentesque erat pellentesque. Suspendisse ornare nulla vitae quam vehicula consectetur. Morbi tincidunt lorem eu...</p>
				<div class="clear"></div>
				</div>

				<a href="blog-details.html" class="link-more">read more</a>
				</div>
				-->
				
			</div>
			<!--/content -->
			<!-- sidebar-->
			<%= render "shared/sidebar" %> <!--/ sidebar -->
			<div class="clear"></div>
		</div>
	</div>
	<!--/ middle -->
	<!-- bottom content/widgets -->
	<%= render "shared/bottomcontent" %> <!--/ bottom content/widgets -->
	<%= render "shared/footer" %>
	<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>

app/views/layouts/create_edit.html.erb
<!DOCTYPE html UTF-8>
<html>
	<head>
		<%= render "shared/stylesheets" %>
	</head>
	<%= render "shared/headbar" %> <!--/ head menu -->
	<%= render "shared/header" %> <!--/ header -->
	<!-- middle -->
	<div class="middle">
		<div class="container_24">
			<!-- featured list -->
			
				<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>

				<%= yield %> <!--
				<div class="post-item">
				<h2><a href="blog-details.html">Top 5 cool Fashion tips for skinny guys</a></h2>

				<div class="post-meta">
				<span class="icon_cat icon_cat_5"><a href="#">Fashion</a></span>
				<em>by <span class="author">Patrick LeBeouf</span> &nbsp;|&nbsp; on Feb 17th 2011 &nbsp;|&nbsp; <a href="#" class="link-comments">43 comments</a></em>

				</div>

				<div class="entry">
				<p><img src="images/temp/temp_image_4.jpg" alt="" width="235" height="164" class="alignleft" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras adipiscing dignissim tortor, molestie sollicitudin erat ullamcorper eu. Nam ornare pharetra sem vitae blandit. Aliquam sed massa vitae risus sodales molestie vitae sit amet arcu. Nunc egestas leo nec est dapibus a pellentesque erat pellentesque. Suspendisse ornare nulla vitae quam vehicula consectetur. Morbi tincidunt lorem eu...</p>
				<div class="clear"></div>
				</div>

				<a href="blog-details.html" class="link-more">read more</a>
				</div>
				-->
				
			</div>
			<!--/content -->
			<!-- sidebar-->
			<%= render "shared/sidebar" %> <!--/ sidebar -->
			<div class="clear"></div>
		</div>
	</div>
	<!--/ middle -->
	<!-- bottom content/widgets -->
	<%= render "shared/bottomcontent" %> <!--/ bottom content/widgets -->
	<%= render "shared/footer" %>
	<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>

app/views/layouts/show_all.html.erb
<!DOCTYPE html UTF-8>
<html>
	<head>
		<%= render "shared/stylesheets" %>
	</head>
	<%= render "shared/headbar" %> <!--/ head menu -->
	<%= render "shared/header" %> <!--/ header -->
	<!-- middle -->
	<div class="middle">
		<div class="container_24">
			<!-- featured list -->
			
				<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>

				<%= yield %> <!--
				<div class="post-item">
				<h2><a href="blog-details.html">Top 5 cool Fashion tips for skinny guys</a></h2>

				<div class="post-meta">
				<span class="icon_cat icon_cat_5"><a href="#">Fashion</a></span>
				<em>by <span class="author">Patrick LeBeouf</span> &nbsp;|&nbsp; on Feb 17th 2011 &nbsp;|&nbsp; <a href="#" class="link-comments">43 comments</a></em>

				</div>

				<div class="entry">
				<p><img src="images/temp/temp_image_4.jpg" alt="" width="235" height="164" class="alignleft" />Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras adipiscing dignissim tortor, molestie sollicitudin erat ullamcorper eu. Nam ornare pharetra sem vitae blandit. Aliquam sed massa vitae risus sodales molestie vitae sit amet arcu. Nunc egestas leo nec est dapibus a pellentesque erat pellentesque. Suspendisse ornare nulla vitae quam vehicula consectetur. Morbi tincidunt lorem eu...</p>
				<div class="clear"></div>
				</div>

				<a href="blog-details.html" class="link-more">read more</a>
				</div>
				-->
				
			</div>
			<!--/content -->
			<!-- sidebar-->
		
			<div class="clear"></div>
		</div>
	</div>
	<!--/ middle -->
	<!-- bottom content/widgets -->
	<%= render "shared/bottomcontent" %> <!--/ bottom content/widgets -->
	<%= render "shared/footer" %>
	<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<% title "NexInnova Home" %>
<%= render "shared/feature"%> <!--/ featured list -->
<div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
	<div class="divider_thin"></div>
	<div class="cat_title">
		<h2>Latest Posts</h2>
		<!-- <div class="sort">
		<a href="#">Popular</a><a href="#" class="active">By Date</a>
		</div> -->
		<div class="clear"></div>
	</div>
	<% for article in @display_articles %>
	<div class="post-item">
		<h2><%= link_to article.title, article_path(article) %></a></h2>
		<div class="post-meta">
			<span class="icon_cat icon_cat_2"><a href="#"><%= article.tag %></a></span>
			<em>by <span class="author"><%= article.author %></span> &nbsp;|&nbsp; on <%= article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"><%= article.comments.count %> comments</a></em>
		</div>
		<div class="entry">
			<p>
				<%= image_tag article.image.url ,:size => '305x206', :class => 'alignleft' %>
			</p>
			<p style="text-align: justify">
				<%= truncate(article.content, :length => 400 , :ommision => "...") %>
			</p>
			<div class="clear"></div>
		</div>
		<%= link_to "read more", article, :class => "link-more" %>
	</div>
	<% end %>
	<div class="other_posts">
		<%= will_paginate @articles, :page_links => false, :next_label => 'Next',  :class => 'prev ' %> <!-- Your page content here, "STATEMENT" -->
		<%= will_paginate @articles, :page_links => false, :previous_label => 'Previous', :class => 'next' %>
	</div>
	

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/show.html.erb
<% title "NexInnova | "+@page.title %> <div class="divider_thin"></div>
<!--content -->
<div class="grid_15 suffix_1 content">
	<% for article in @page_articles %>
	<div class="post-item">
		<h2><a href="blog-details.html"><%= article.title %></a></h2>
		<div class="post-meta">
			<span class="icon_cat icon_cat_2"><a href="#"><%= article.tag %></a></span>
			<em>by <span class="author"><%= article.author %></span> &nbsp;|&nbsp; on <%= article.created_at.to_s(:long) %> &nbsp;|&nbsp; <a href="#" class="link-comments"><%= article.comments.count %> comments</a></em>
		</div>
		<div class="entry">
			<p>
				<%= image_tag article.image.url ,:size => '305x206', :class => 'alignleft' %>
			</p>
			<p style="text-align: justify">
				<%= truncate(article.content, :length => 400 , :ommision => "...") %>
			</p>
			<div class="clear"></div>
		</div>
		<%= link_to "read more", article, :class => "link-more" %>
	</div>
	<% end %>

app/views/shared/_bottomcontent.html.erb
<div class="bottom_content">
	<div class="container_24">
		<div class="inner">
			<div class="grid_6">
				<div class="widget">
					<ul class="menu_type_1">
						<% for page in @pages %>
						<li>
							<%= link_to page.title, page_path(page) %>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>NETWORK</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">All Sports Mag</a>
						</li>
						<li>
							<a href="#">Car Tuning Mag</a>
						</li>
						<li>
							<a href="#">For Her Magazine</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>BLOG</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">We've redesigned the blog...</a>
						</li>
						<li>
							<a href="#">Saving everything in your...</a>
						</li>
						<li>
							<a href="#">Make it right, now!</a>
						</li>
						<li>
							<a href="#">Asylum of fools discovered</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="grid_6">
				<div class="widget">
					<h3>MAGAZINE</h3>
					<ul class="menu_type_2">
						<li>
							<a href="#">Our authors</a>
						</li>
						<li>
							<a href="#">Monthly Archive</a>
						</li>
						<li>
							<a href="#">Advertise</a>
						</li>
						<li>
							<a href="#">Jobs &amp; Careers</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>

app/views/shared/_feature.html.erb
<div id="feature_list">
	<ul id="feature_tabs">
		<% for article in @latest_articles %>
		<li>
			<span class="link-title"> <%= article.title %> </span>
			<div class="feature_cat">
				<span class="icon_cat icon_cat_1"> <%= article.tag %></span><a href="blog-details.html" class="link-more"><%= link_to "Read more", article_path(article) %></a>
			</div>
		</li>
		<%end %>
	</ul>
	<ul id="feature_output">
		<% for article in @latest_articles %>
		<li>
			<%=image_tag article.image.url, :size => "960x325" %>
			<!-- <img src="images/temp/temp_featured_1.jpg" width="960" height="325" alt="" />   -->	
			<a href="blog-details.html"></a>
		</li>
		<% end %>
	</ul>
</div>
<div class="divider_thin"></div>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="container_24">
		<div class="botmenu">
			<ul>
				<% for page in @pages%>
				
				<li class="menu-red">
								<%= link_to page.title, page_path(page) %>
				</li>
				<% end %>
				
			</ul>
			<div class="clear"></div>
		</div>
		<div class="footer_logo">
			<%= link_to image_tag('logo.png', :alt =>'Show', :size => '277x77'), root_path %> 
			
		</div>
		<p class="copyright">
			&copy; 2011 |  <a href="http://www.nexinnovaadvisorygroup.com/">NexInnova Advisory Group</a>.  All rights Reserved. <a href="#">Privacy Policy</a> | <a href="#">Terms &amp; Conditions</a>
		</p>
	</div>
</div>

app/views/shared/_headbar.html.erb
<div class="head_bar">
	<div class="container_24">
		<ul class="dropdown">
			<% if !user_signed_in? %>
			<li>
				<%= link_to_rpx "Sign In Using FB or Twitter", user_session_url %>
			</li>
			<li>
				<%= link_to "Sign In", user_session_url %>
			</li>
			<% else %>
			<li>
				Signed in as <%= current_user.email %>
			</li>
			<li>
				<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			</li>
			<% end %>
		</ul>
		<div class="clear"></div>
	</div>
</div>